---
engines:
  phpcs:
    enabled: true
    php_version: 7.3
    exclude_paths:
      - 'source/**'
  eslint:
    enabled: true
    exclude_paths:
      - '**/*.svg'
languages:
  php:
    extensions:
      - '.php'
exclude_paths:
  - 'css/**'
  - 'images/**'
  - 'js/dist/**'
  - 'js/libraries/**'
  - 'node_modules/**'
  - 'vendor/**'
