---
engines:
  phpcs:
    enabled: true
    php_version: 7.3
    exclude_paths:
      - '/source'
  eslint:
    enabled: true
languages:
  php:
    extensions:
      - '.php'
exclude_paths:
  - '/images'
  - '/node_modules'
  - '/vendor'
