---
engines:
  phpcs:
    enabled: true
    php_version: 7.3
  eslint:
    enabled: true
languages:
  php:
    extensions:
      - '.php'
exclude_paths:
  - 'images'
  - 'node_modules'
  - 'source'
  - 'vendor'
